# Generated by Django 3.2.8 on 2021-10-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='store.store')),
            ],
        ),
    ]
